"""remove unique constraints

Revision ID: d137e5c09b6c
Revises: f822d4639df2
Create Date: 2024-07-20 01:53:16.755182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd137e5c09b6c'
down_revision = 'f822d4639df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('consultations_assitance_psychologist_key', 'consultations', type_='unique')
    op.drop_constraint('consultations_children_key', 'consultations', type_='unique')
    op.drop_constraint('consultations_type_psychologist_key', 'consultations', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_address_key', 'users', type_='unique')
    op.drop_constraint('users_age_key', 'users', type_='unique')
    op.drop_constraint('users_civil_status_key', 'users', type_='unique')
    op.drop_constraint('users_date_of_birth_key', 'users', type_='unique')
    op.drop_constraint('users_emergency_number_key', 'users', type_='unique')
    op.drop_constraint('users_gender_key', 'users', type_='unique')
    op.drop_constraint('users_municipality_key', 'users', type_='unique')
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_constraint('users_registration_key', 'users', type_='unique')
    op.drop_constraint('users_religion_key', 'users', type_='unique')
    op.drop_constraint('users_tutor_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_tutor_key', 'users', ['tutor'])
    op.create_unique_constraint('users_religion_key', 'users', ['religion'])
    op.create_unique_constraint('users_registration_key', 'users', ['registration'])
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.create_unique_constraint('users_municipality_key', 'users', ['municipality'])
    op.create_unique_constraint('users_gender_key', 'users', ['gender'])
    op.create_unique_constraint('users_emergency_number_key', 'users', ['emergency_number'])
    op.create_unique_constraint('users_date_of_birth_key', 'users', ['date_of_birth'])
    op.create_unique_constraint('users_civil_status_key', 'users', ['civil_status'])
    op.create_unique_constraint('users_age_key', 'users', ['age'])
    op.create_unique_constraint('users_address_key', 'users', ['address'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('consultations_type_psychologist_key', 'consultations', ['type_psychologist'])
    op.create_unique_constraint('consultations_children_key', 'consultations', ['children'])
    op.create_unique_constraint('consultations_assitance_psychologist_key', 'consultations', ['assitance_psychologist'])
    # ### end Alembic commands ###
